### PR TITLE
Fix compatibility with mesa 18.3 in F29

### PR DESCRIPTION
**Pull request by petefwalter**
https://bodhi.fedoraproject.org/updates/FEDORA-2019-cefa2d1b59

### CODE REVIEW

**Comment by kwizart** [comment]
Thx for the notice, I've merged the changes in the package. Will be pushed to stable in few days.

**Comment by kwizart** [comment]
Seems like there is a build failure... Does it needs an updated mesa or else ?
http://koji.rpmfusion.org/kojifiles/work/tasks/5436/295436/build.log

**Comment by petefwalter** [comment]
Thanks! Ah, yes, I think it needs libva 2.4.0. Want me to update it in F29 and add it to the same mesa update?

**Comment by kwizart** [comment]
Well, the problem is that updating libva usually means changing the va_init function to adap to the 2.4.0 version
That would means at least rebuilding the whole multimedia stack in rpmfusion to get the package behave in a consistent way across rebuild.

Given the workload involved this is more something that should be done on a development basis only.
As such I would suggest to revert the mesa change that lead to that issue in vaapi instead.

**Comment by petefwalter** [comment]
Sad, a lot of people were asking for a mesa update for new hardware support :( Oh well.

**Comment by kwizart** [comment]
Well, nothing prevent this to appear on a copr repo what's the problem with that ?

**Comment by petefwalter** [comment]
I've unpushed the mesa update. Sorry for the trouble.

**Comment by paulcarroty** [comment]
@petefwalter why you unpushed it? libva 2.4 works great with this patch!

If someone want to try it - all packages are available in my [Copr](https://copr.fedorainfracloud.org/coprs/paulcarroty/mesa-from-rawhide/).

**Comment by petefwalter** [comment]
@paulcarroty We don't have libva 2.4 in F29 and the libva maintainer doesn't want to update it.

**Comment by paulcarroty** [comment]
:man_facepalming:

**Comment by mooninite** [comment]
@kwizart So libva is breaking ABI without a SONAME bump? 2.3 and 2.4 have the same SONAME version.

**Comment by HolimaX** [comment]
@petefwalter , @paulcarroty , @mooninite thank you guys for getting involved. As I find this quite sad, even if I a, AMD RX 580 owner, I will do what I can - spread the word as attempt to get people involved. https://twitter.com/HX_ub/status/1095941553099624448 https://www.facebook.com/linards.liep/posts/2219799898050828 https://plus.google.com/+LinardsLiepi%C5%86%C5%A1LV/posts/GbhCpTKhGak

**Comment by kwizart** [comment]
I haven't talked about ABI changes, but the libva-vdpau-driver will need to be rebuilt to pick the new interface name due to the insane way libva defines the init function using minor version check.

So with more checking I'm updating libva-2.4.0 in f29.

Please remind that I'm 900% of my free time to fix existing issues in stable and development fedora releases. So I'm naturally reluctant to move bugs everywhere. Specially as the community is going into selfish copr repos than contribute on the real development area.

**Comment by kwizart** [comment]
Just want to re-affirm my point.

We really need a stable (1)  copr repo with an updated mesa from stable/master/next branches. on current fedora (if not rawhide also).
This should really works as a CI to get the current mesa work when needed and no matters why.
Occasionally, it should be possible to update Fedora on mesa, but with known feedbacks.

Updated libva-2.4.0 package:
https://bodhi.fedoraproject.org/updates/libva-2.4.0-2.fc29%20libva-vdpau-driver-0.7.4-24.fc29

(1) By stable, I mean using a stable and well known URL for copr 
There are already lot of self maintained copr repo related to mesa, but having a community based one worth it.
https://copr.fedorainfracloud.org/coprs/fulltext/?fulltext=mesa

**Comment by HolimaX** [comment]
> Just want to re-affirm my point.
> 
> We really need a stable (1) copr repo with an updated mesa from stable/master/next branches. on current fedora (if not rawhide also).
> This should really works as a CI to get the current mesa work when needed and no matters why.
> Occasionally, it should be possible to update Fedora on mesa, but with known feedbacks.
> 
> Updated libva-2.4.0 package:
> https://bodhi.fedoraproject.org/updates/libva-2.4.0-2.fc29%20libva-vdpau-driver-0.7.4-24.fc29
> 
> (1) By stable, I mean using a stable and well known URL for copr
> There are already lot of self maintained copr repo related to mesa, but having a community based one worth it.
> https://copr.fedorainfracloud.org/coprs/fulltext/?fulltext=mesa

If I may comment here, gentleman, 
I personally fully agree and support you. Jet what is an valid note is that this has been working in so big variety of hardware (many hybrids with multiple GPus/iGPUs) and it is 3rd patch version for Mesa in 18.3.x branch, so hard to imagine to find some really serious regression. I believe if the official repo maintainer knows where to look for getting the right codebase change implemented, that this also means that the repos referenced like this are stable and well known.

**Comment by petefwalter** [comment]
Thanks @kwizart!

**Pull request closed without merging**
